name: cache-events
on:
  schedule:
    - cron: "*/15 0-4 * * *"
  workflow_dispatch:

jobs:
  trigger-cache-events:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: curl https://schwarz-bunte-seiten-berlin.org/cache-events
