name: parse-osm
on:
  schedule:
    - cron: "0 5 1 * *"
  workflow_dispatch:

jobs:
  trigger-parse-osm:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: curl https://schwarz-bunte-seiten-berlin.org/parse-osm-data
